site_name:        MixedModels.jl
repo_url:         https://github.com/dmbates/MixedModels.jl
site_description: Fit and examine linear mixed-effects models
site_author:      Douglas M. Bates

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - Fitting: man/fitting.md
- Library:
  - Public: lib/public.md
  - Internals: lib/internals.md
